# Generated by Django 4.2.6 on 2023-10-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=35)),
                ('Address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=6)),
                ('card_no', models.CharField(max_length=20, unique=True)),
                ('exp_month', models.CharField(max_length=2)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SignupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35, unique=True)),
                ('email', models.CharField(max_length=60)),
                ('phonenumber', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('reenterpassword', models.CharField(max_length=20)),
            ],
        ),
    ]
